= Documentation as Code: Balancing Writing & Delivery with Asciidoctor
Dan Allen <https://github.com/mojavelinux[@mojavelinux]>

[abstract]
--
// tag:abstract[]
Producing good documentation requires as much engineering ability as it does writing talent.
But all too often, we focus on the needs of one group while tormenting the other with a cumbersome process.
In this talk, I'll explain how managing documentation as code balances roles, responsibilities & delivery to produce the best documentation product.

For the writer, the AsciiDoc markup language takes the pain out of writing, keeps content separate from presentation, and makes the documentation source control friendly.
The Asciidoctor processor enables the engineer to transform this plain text content into a variety of presentation formats for distribution to multiple channels and audiences.
Together, these two groups can collaborate like never before by leveraging a proven workflow based on source control, automation, and continuous delivery.

Come discover how to get more out of your technical content by writing it in AsciiDoc and transforming it with Asciidoctor.
// end:abstract[]
--

== View online

https://opendevise.github.io/presentation-documentation-as-code[Slides]
&middot;
https://github.com/opendevise/presentation-documentation-as-code/blob/master/src/notes/script.adoc[Script]

== Build and view slides locally

First, ensure you have the following installed:

. http://nodejs.org[Node.js]
. http://gulpjs.com[Gulp CLI]

 $ npm install -g gulp-cli

. https://www.ruby-lang.org/[Ruby >= 2]

 $ rvm use 2.3.1 --install

. http://bundler.io/[Bundler]

 $ gem install bundler

Next, install dependencies (if not already installed by the generator):

 $ npm install
   bundle install --path=.bundle/gems

Finally, build and serve the presentation!

 $ gulp serve
