= Write in AsciiDoc, Publish Everywhere: Transcript

icon:tv[id=title]
// tag::title[]
Welcome.

Today, we're going to take a look at how you can write in AsciiDoc and publish everywhere.
// end::title[]

icon:tv[id=print-shop-box]
// tag::print-shop-box[]
When I was young, my parents got my siblings and I our first computer, an Apple II, along with a printer, the ImageWriter.
One of our favorite programs to use was The Print Shop.
// end::print-shop-box[]

icon:tv[id=print-shop-select]
// tag::print-shop-select[]
Using this program, we could make signs, banners, or greeting cards using an assortment of block-style fonts, clip art, and patterned borders (and, to be sure, we made a lot).

We'd then send the job off to the printer to transform our creation into something that existed in the real world.
// end::print-shop-select[]

icon:tv[id=print-long-banner]
// tag::print-long-banner[]
//Naturally, the printing step of the Print Shop was the highlight.
Back then, printing was the only way to share what you had created; to make your statement.
People didn't have screens in their pockets.
We adorned our doors and walls with these statements, our favorite being *Keep Out* with a skull and crossbones.
Happy Birthday was another popular phrase.
It was our version of the web page.

I remember thinking, "`OMG, we can make it say anything we want! What do we want to say?`"

It was my first experience publishing content.
And it felt amazing.
That power of being able to write something and have it be transformed into something material.
The power to express oneself.
To inform.
// end::print-long-banner[]

icon:tv[id=color-ribbon-cartridge]
// tag::color-ribbon-cartridge[]
I was particularly enthralled by the printing process.
The printer had a ribbon cartridge, which would get dragged across the paper to leave its marks.
When we sent it one of our creations, it would launch into a flurry of activity, seemingly in a panic to strike each dot onto the matrix.
I often wondered if it knew what it was making as the meaning was revealed ever so gradually.
// end::color-ribbon-cartridge[]

icon:tv[id=print-banner]
// tag::print-banner[]
The speed, or rather lack thereof, was significant because it meant we had to choose our content--our message--wisely.
Picture the young group of kids, all vying to put a message out into the world, huddled around the screen barking out words to bring to life.
It was not only my first publishing experience, but also my first collaborative one.
// end::print-banner[]

== Introduction

icon:tv[id=many-masters]
// tag::many-masters[]
Our technical content today has much to say and serves many masters, just as the content did in that childhood print shop.
//Content lives many lives and serves many masters.
Therefore, it's essential for your content workflow to be flexible enough to meet those demands.
// end::many-masters[]

icon:tv[id=separate]
// tag::separate[]
I'm not the first--and I won't be the last--to say that the best way to ensure this flexibility is to have a separation of content and presentation (and even the infrastructure that makes the presentation possible).
This way, you are able to meet the needs of the various stakeholders.
But there's a careful balance that must be achieved to avoid hindering creation, publication, and collaboration.
It's a balance that I believe AsciiDoc strikes.
I'll explain why in this talk.
// end::separate[]

//When evaluating a content system for creating technical documentation, you should consider two questions:
//
//* What are the capabilities of the content system?
//* How do those capabilities align with your needs?

icon:tv[id=agenda]
// tag::agenda[]
I believe we should consider three key capabilities when evaluating the value proposition of a content system.

. Creation
. Publication
. Collaboration

We'll evaluate AsciiDoc through the lens of these three capabilities to investigate its strengths and learn/discover how to get the most out of them.
// visual concept: show magnifying glass overlay on list
// end::agenda[]

== Creation

icon:tv[id=creation]
// tag::creation[]
All other things aside, content is king.
A content system that doesn't consider the needs of the author first is not sustainable and thus doomed for failure.
So the spotlight of this first section is on the writers in the room.
This is for you.
// end::creation[]

icon:tv[id=confined]
// tag::confined[]
Before I get into AsciiDoc, I want to briefly peek a glimpse at DocBook and LaTeX so we have something to contrast against. 

Content systems often leave you feeling very confined.
Perhaps some of you can atest to this.
The struggle is real.
// end::confined[]

icon:tv[id=docbook]
// tag::docbook[]
DocBook is an XML schema that's highly structured and semantic with a keen focus on separating content from presentation.

Here's how it looks:
// end::docbook[]

<figure:DocBook sample>
O_o

icon:tv[id=docbook-critique-a]
// tag::docbook-critique-a[]
This was clearly made by an engineer while the writer was out.
It screams, "`I don't care about your needs. I just need you to satisfy mine.`"
// end::docbook-critique-a[]

icon:tv[id=docbook-critique-b]
// tag::docbook-critique-b[]
Writers often get a sense that their content is locked up in this structure, and sense the burden of having to remember all the tags and when to use them.
It's necessary to supplement every piece of content with an enclosure of markup since nothing is implied
The ironic part is that the engineer didn't do herself much of a service either.
XML tools--especially the ones in this toolchain like XSLT--are a pain to work with.

Nobody wins here.
// end::docbook-critique-b[]

icon:tv[id=latex]
// tag::latex[]
Moving on, let's look at LaTeX.

Here's how that looks:
// end::latex[]

<figure:LaTeX sample>
O_o

icon:tv[id=latex-critique-a]
// tag::latex-critique-a[]
This was clearly made by yet another engineer while the writer was away.
It screams, "`I don't see the difference between content and presentation/layout, so I'll just mix all the concerns together.`"
// end::latex-critique-a[]

icon:tv[id=latex-critique-b]
// tag::latex-critique-b[]
Writers get lost not only because the content is locked up in this bird nest, but now there's a deluge of dialects that no mere mortal can possibly remember; like a mud flow washing over their content.
It's hard to imagine something less welcoming.
// end::latex-critique-b[]

icon:tv[id=got-pdf]
// tag::got-pdf[]
The other major problem is that LaTeX was not designed with multi-channel web publishing in mind.
Got PDF?
I could go on, but the point is, many content systems cater more (even exclusively) to the technologist rather than the writer.
// end::got-pdf[]

icon:tv[id=asciidoc]
// tag::asciidoc[]
Let's get that writer back in here and make her the dignitary.

After getting to know her needs, we create something called AsciiDoc.
Here's the markup we present her:
// end::asciidoc[]

<figure:AsciiDoc sample>
\o/

icon:tv[id=asciidoc-critique]
// tag::asciidoc-critique[]
Yummy.

Somewhere in the distance you hear the writer singing, "`I can see clearly now, the tags are gone.`"
// end::asciidoc-critique[]

The first thing you'll notice is that the syntax is clear & concise.
What you see is predominently content.
It's readable in raw form, unlike other formats we've seen.
"`Perfection is achieved not when there's nothing more to add, but when there's nothing left to take away`" - Antoine de Saint-Exubéry
Paragraphs are just paragraphs, no bullshit.
The remaining marks are based on familiar conventions, such as asterisks to itemize a list or equal signs to designate section titles.
Words that appear in the syntax are selected from common terminology like "source" and "image".
In general, the syntax is remarkably forgiving (unlike DocBook, which is extremely picky), making it less daunting.
If you dig a bit deeper, you'll notice there's a consistency to the syntax.
Indeed, the language is based on repeatable patterns (and is extended by following those same patterns, which we'll get into later).
Finally, the syntax is extremely semantic.
Each bit of content belongs to a node, a content block or phrase.
These "`nodes`" can be annotated with extra bits of information that states what the content is, how it might be presented, and other properties.
The most practical are roles.
<figure:Example of roles; annotate a path; roles on slides>
This ability to add metadata to content not only encourages the separation of content and presentation, it also informs transformation, which we'll get into next.
// QUESTION should point about line-oriented/left-align go right at beginning, before other characteristics?
One reason the syntax is simple and consistent is because it's both line-oriented and left-aligned.
The line-oriented aspect allows AsciiDoc to best leverage the medium.
A lot can be said by isolating characters by line.
Take delimited blocks for instance.
You can add these "`fences`", then AsciiDoc can assume everything inside is content for that block.
<figure:delimited block>
Having a syntax that is aligned to the left margin helps keeps the writer rooted.
You needn't worry how many spaces are needed and content doesn't float out into the ether.
You rely on the line-oriented fences to encompass the content instead.
What isn't here?
WYSIWYG.
<figure:YGWYG ¯\_(ツ)_/¯>
Why?
You don't need it.
AsciiDoc is readable in raw form.
WYSIWYG takes away control and puts a barrier between you and your content.
But it doesn't mean there are no tools.
There certainly are.
In fact, I continue to advocate for the development of an IDE for writers.
For instance, if you feel like you need to preview in real time, as many authors do, that's still possible.
Nothing is lost, but a lot of control is preserved.
Suggest authoring in Atom with the AsciiDoc add-on to get helpful syntax highlighting.
<figure:Atom editor>
Also mention AsciidocFX and IntelliJ IDEA.
<figure:AsciidocFX>

icon:tv[id=creation-recommended-practices]
// tag::creation-recommended-practices[]
If I were to list all the details of AsciiDoc, it'd be overwhelming.
For sure, there's a lot in there.
But what you find is that shops tend to standardize on a cross section of it.
Dialects bring additional consistency to the language and reinfoce the impression of simplicity.
I also recommend setting up templates for common document types, one to ensure consistency, but also to allow the writer to jump right into the writing phase.
Another way to simplify creation is to partition the content.
After awhile, having all the information in one document becomes unwieldy.
You might want to split up a book by chapters, including common or shared content, or extract code samples so they don't get mixed up in content.
AsciiDoc supports all that through it's include mechanism.
It even goes so far as to allow you to include fragments of another document (by line number or tagged region).
One way this feature is used is to make testable documentation.
Code snippets can be pulled in from a test suite, where the code can be tested in isolation.
It's also just nice to get all your code samples out of the writer's hair.
Since includes can span repository boundaries and even be fetched from a URL, you can achieve a "`single source of truth`" (instead of copy/paste)
AsciiDoc's attributes are another way to inject dynamic or reusable content into the document.
Of course, once you start dividing up your document, you'll want to be able to create references between them.
AsciiDoc supports both internal and inter-document references, and there are ways to extend this capability.
//Check out AsciiDoc syntax quick reference, Awesome Asciidoctor.
// end::creation-recommended-practices[]

icon:tv[id=migration]
// tag::migration[]
So you might be thinking, all this is great, but I have existing content.
How do I get it into AsciiDoc?
We'll, conversion to AsciiDoc is relatively easy.
Many groups have done it and a number of tools are available to help.
The reason it's relatively easy stems from the simplicity of the language itself.
One such tool is DocBookRx, which converts form DocBook to AsciiDoc.
(PSA about pandoc).
// QUESTION move warning to end of talk?
As a word of warning, if you do migrate to AsciiDoc, make sure you leave yourself enough time to make it a clean as possible before you let the writers loose on it.
It's much easier (and less expensive) to fix cross-cutting problems at the beginning rather than while everything is changing.
// end::migration[]

icon:tv[id=dawn]
// tag::dawn[]
So far we've just talked about the source, the domain of the writer.
Now that you have content in AsciiDoc, what can you do with it?
The AsciiDoc syntax is so simple and elegant, it's easy to be deceived that it can only produce primitive output.
You couldn't be more mistaken.
The AsciiDoc content is just the raw material, its semantics the seeds of the blossoms that we'll produce.
Let's shed some light on how we can transform it and where we can publish it.

It's the dawn of endless possiblities, just like the Print Shop was for us.
// end::dawn[]

== Publication

icon:tv[id=publication]
// tag::publication[]
The focus of this section is the AsciiDoc processor & publisher, Asciidoctor.
Engineers, wake up, this is for you.
// end::publication[]

icon:tv[id=conversion]
// tag::conversion[]
I want to start by mentioning that, out of the box, Asciidoctor can convert to HTML and DocBook, allowing you to preview and export the content, respectively.
This is just the default interpretation of the AsciiDoc source.
There's nothing stopping you from interpreting the source in a different way.
That's what separation of content and presentation affords you.
Every bit of output that gets generated can be customized in one way or another.
You should look at the AsciiDoc source as a source of record, not a textual representation of the output.
// end::conversion[]

I'll cite a few examples to get you thinking about what is possible.
tabs, background image for slide, import PDF page, slide notes
What we're talking about here is transformation.
Transformation is the key to being able to publish to multiple channels in a variety of formats.
When Asciidoctor reads the file, it builds an AST, or abstract syntax tree.
That tree is passed to a converter, which than transforms it into the target format, such as HTML.
One way to extend Asciidoctor is to write a custom converter, or build on one that already exists.
The only limit to what output formats you can produce is what you're willing/able to create.
But even before the tree is sent to the converter, you have a chance to manipulate it or mine it for information.
In fact, you don't even need to output anything.
You can just use the AST to query the document for information in a contextual way (unlike grep, which is crude and blind to context)
This stuff literally makes me giddy.
You can even go one step further and tap into the parser itself.
Asciidoctor provides an extension API to allow you to add additional elements to the syntax, such as a custom block or macro.
<Example of syntax extension>
As you can see, you have a lot of control over how the AsciiDoc is interpretted.
Be careful not to fall into the trap of thinking that one input document produces one output document.
You could take one input document that represents a book and produce multiple pages of HTML.
You can also go the other way.
You could use the processor, or a toolchain that wraps it, that takes input from several sources and weaves them together.
Where we see this technique used is in API documentation tools like Spring REST Docs and swagger2markup, which generate AsciiDoc to document the API methods, then combine it with content written by the author and produces a document (or documents) to be published.
Part generated, part scribed.
The toolchain plays the role of orchestrator, weaving together disparate content sources.
There truly are endless possibilities for your content once in this format and managed by this toolchain.
This transformation capability also keeps you from being tied down.
Just as you can generate formats for publishing, you can generate to another source format, even AsciiDoc.
If you store the source in a version control system, which we'll talk more about in the next section, the publication tool can even tap into the document history and inject content such as an audit log or make different versions of the document available.
This is another powerful way to keep your content DRY and free from doing tasks for information that can be implied.
//You could extend the abstraction even further and avoid coupling the path of the source file with the output path.
//Instead, give each document a business ID so you can move files around and still produce the same output structure.

icon:tv[id=publication-recommended-practices]
// tag::publication-recommended-practices[]
Last but not least, publication should be fully managed by an automated build.
It doesn't end with Asciidoctor.
The build should not only handle converting the content and publishing it to the various channels, but should describe and manage the infrastructure as well.
Treat your docs just like you would any other application.
It should be possible to "`push to publish`" and the computer takes over from there.
These automated builds also aid with collaboration, which we'll get into next.
What you'll find is that AsciiDoc lends itself very well to collaboration because much of the tools we need are already in place.
While there's a bit more assembly required up front, what you'll likely find is that it blows any sort of proprietary, closed system out of the water.
// end::publication-recommended-practices[]

== Collaboration

icon:tv[id=collaboration]
// tag::collaboration[]
This section addresses both the writers and the engineers, and anyone else involved in the content effort.
No doubt what makes AsciiDoc ripe for collaboration above all else is that it is version-control friendly.
AsciiDoc doesn't have "`source control support,`" rather it just lends itself to being source controlled.
No binary blobs, just plain text.
And version-control systems love plain text.
You get history, source diffs, rich diffs, branching, merging, etc., all which can be managed with interfaces like GitHub and GitLab.
// end::collaboration[]

And this is a real force for contribution, as the JBoss BxMS and OpenShit teams have both observed:
> The OpenShift team, who had undertaken a similar effort, reported that after the migration from DocBook to AsciiDoc, the rate of both internal and external contributions skyrocketed—from several a year to several a week.
> Even without much announcement, mere days after the migration, we started seeing incoming Merge Requests in GitLab, where there were none before.
> It may be too soon to judge, but preliminary results hint that this indeed is an observable trend.
Nothing drives that more, invites participation more, than the "`Edit on GitHub`" link.
<figure:Edit on GitHub link>
It's impossible to overstate the significance of GitHub (and, increasingly, GitLab).
These interfaces have proven to be incredibly approachable and encourage contribution.
You can benefit from that phenomenon by moving your documentation there.
But the team does need to understand how the "`Edit on GitHub`" process actually works and know how to manage the git workflow.
I do strongly recommend investing in git training for your team.
Knowing how to use git correctly will save time and toes.
All this leads to a strong-held belief of ours.
Docs = Code
Why is that interesting?
Well, we have a long history in this industry of collaborating on code.
If we view docs as just another form of code, we can benefit from all of its processes, pratices, techniques, and tools.
One of the first tools that comes to mind is code review.
Countless CMS tools have tried to manufacture a content review workflow.
Well, we have one right here, (built on an accepted industry practice), supported by incredible code review tools like Gerrit, GitHub, GitLab, and so forth.
<Screenshot of GitHub rich diff>
Given that AsciiDoc is just plain text, like developers, writers can use their own tools in their own writing environment.
No need for special, proprietary, foreign, costly tools.
In fact, you really should avoid imposing tool/editor choices.
You can work in isolation, then just push to publish.
Why is this important?
"`Happy people collaborate well`" (or are more inclined to).
How do you coordinate efforts?
Use an issue tracker to manage bugs, improvements, and content initiatives.
You can then see content progress as it moves across the issue board.
<figure:issue board>
Mention the issue when submitting the pull request that resolves it.
Just like code.
This system is also advantageous to the manager.
It makes it easy for managers to moniter the workflow, such as to determine what changed or what work was done, simply by looking at the git history or activity charts on GitHub and GitLab.
<figure:git history>

icon:tv[id=collaboration-recommended-practices]
// tag::collaboration-recommended-practices[]
Although AsciiDoc is naturally friendly to version-control systems, there are ways to organize the content that let you get even more out of it.
For instance, I highly recommend writing with a sentence-per-line style.
By doing so, you isolate changes to the line of content that they affect, much like changing a line of code.
If you use fixed-column hard-wrapping, the change at the beginning of a paragraph can have a cascading effect, possibly interfering with unrelated lines that someone else is modifying.
In general, you want to look for ways that allow you to work in different parts of a file without causing conflicts.
Isolate your changes.
Another way to avoid such conflicts is to use well-factored, modular content.
You want a consistent, intuitive, and discoverable structure.
Consider using the topic-based authoring method so the content can be stored separately from the files that aggregate it.
As mentioned before, import non-content such as code snippets from the original source file (possibly even in a separate repository) so that it can be managed independently and doesn't fall out of date.
// TODO mention git lfs
It's best to have a style guide: for syntax; for structure; for patterns; for voice.
Automate the human process.
This reduces the amount of thought, avoids errors, and drastically cuts down on expensive micro-migrations to fix mistakes.
Again, the document templates mentioned earlier benefit collaboration as well.
Validation tools are also important because they help ensure quality and consistency.
You can tap into the Asciidoctor process to perform validations in addition to the ones that come out of the box.
Don't fall into the trap of putting all your content in a single repository.
Instead, organize your repositories by software product or logical product group.
We can refer to this repository as a "`content container.`" (a contrast to a "`library layout`" where there's one directory per book)
You can then assume that all the content in a single repository is versioned together.
If different documents have different versioning schemes, or move at different rates, that's an indicator you should move them to separate repositories.
Also avoid creating monolithic documents.
In particular, beware of the Russian Doll Effect (contributing guide inside developer guide inside of README).
It's easy to create a script that brings them all back together.
The reason this partitioning is important is because it enables you to leverage branches properly.
Have a branch for each major release line.
Different major (and maybe even minor) versions of the document should be stored in separate branches.
Don't use different directories to store the versions, as I've seen some teams do.
You lose a lot of capabilities of the version control system by not using branches because the commands for those systems don't understand how to compare documents that way.
It's also much harder to search for content.
Take a look at AsciiBinder for an example of a build system that builds out versions of the documentation from the branches.
Regardless of what structure you choose, anyone should be able to build the output through a simple interface, without having to remember complex commands.
That's why it's important to have an automated build, which obviously benefits publication as discussed earlier.
// end::collaboration-recommended-practices[]
TODO need a wrap-up/transition

(See https://www.youtube.com/watch?v=JvRd7MmAxPw&list=PLZAeFn6dfHpnN8fXXHwPtPY33aLGGhYLJ&index=20)

== Conclusion

In this talk, we evaluated AsciiDoc through the lens of three capabilities:

. Creation
. Publication
. Collaboration

In any content system, the writer must be the focus, first and foremost.
Otherwise, the system is destined for failure.
It's vital to protect the sanctity of writing.
But the engineer must be empowered as well to transform that content.
Content that's locked away cannot serve its function, cannot reach its users across channels.
Like the technology that it documents, technical writing benefits from many eyes and minds.
Anything inherently complex does.
So the system must be friendly to collaboration.
It's the key to getting contributions as well.
As we've seen, the Asciidoctor toolchain, from the AsciiDoc language to the Asciidoctor processor, extensions, converters, and tools, strikes this balance.
These capabilities happen to be the three pillars of the Asciidoctor project, so we expect the story to only get better.
Write in AsciiDoc, publish everywhere!
Thank you!
